version: '3.8'

services:
  oracle:
    image: gvenzl/oracle-free:latest
    ports:
      - "1521:1521"
#      - "5500:5500"
    environment:
      ORACLE_RANDOM_PASSWORD: "true"
    volumes:
      - ./scripts/init.sql:/container-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "1521" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - consumer
    restart: always

  zookeeper:
    image: zookeeper:3.7
    ports:
      - "2181:2181"
    networks:
      - consumer

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
    depends_on:
      - zookeeper
    networks:
      - consumer

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - oracle
      - kafka
    env_file: ".env"
    ports:
      - "8080:8080"
    networks:
      - consumer
    restart: always

networks:
  consumer:
    driver: bridge

volumes:
  oracle-data: